name: movie_checker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_svg: ^2.0.10
  darq: ^2.0.0
  injectable: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_gen: ^5.4.0
  get_it: ^7.7.0
  provider: ^6.1.2
  equatable: ^2.0.5
  result_dart: ^1.1.1
  shared_preferences: ^2.3.1
  firebase_core: ^3.14.0
  firebase_database: ^11.3.7
  auto_route: ^10.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^2.4.2
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0

flutter:
  assets:
    - assets/icons/
  generate: true
  uses-material-design: true
